name: Manual Drift Detection Agent Version

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to sync configurations to'
        required: true
        default: 'main'

jobs:
  sync-configurations:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ARGOCD_GITOPS_VERSIONS_DEPLOYMENT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout source repository (current repo)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we fetch all history for diffs

      - name: Checkout target repository using SSH
        uses: actions/checkout@v2
        with:
          repository: 'redreveal/argocd-gitops-versions'
          ssh-key: ${{ secrets.ARGOCD_GITOPS_VERSIONS_DEPLOYMENT_KEY }}
          path: target-repo
          ref: ${{ github.event.inputs.target_branch }}

      - name: Install Python and PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pyyaml

      - name: Compare and Update Configuration Files
        id: process_configs
        run: |
          changes_detected=false
          src_dir="$GITHUB_WORKSPACE/versions"
          trg_dir="$GITHUB_WORKSPACE/target-repo/processing/versions"
          for src_file in $(find $src_dir -name "processing-agent-config.yml"); do
            trg_file="${src_file/$src_dir/$trg_dir}"
            trg_file="${trg_file/processing-agent-config.yml/values.yaml}"
            echo "Checking $src_file against $trg_file"
            python3 ./.github/actions/scripts/drift_detection_configs.py "$src_file" "$trg_file"
            if [ $? -eq 0 ]; then
              echo "Updating due to differences: $src_file -> $trg_file"
              python3 ./.github/actions/scripts/process_values_to_cm.py "$src_file" "$trg_file"
              changes_detected=true
            fi
          done
          echo "::set-output name=changes_detected::$changes_detected"
        shell: bash

      - name: Commit and Push Changes to Target Repository
        if: steps.process_configs.outputs.changes_detected == 'true'
        run: |
          cd $GITHUB_WORKSPACE/target-repo
          git config user.email "rberisha@revealdata.com"
          git config user.name "Redon Berisha"
          git add versions/
          git commit -m "Updated configurations based on changes in drift detection"
          git push
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa"
