name: Manual Sync Configuration

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to sync configurations to'
        required: true
        default: 'main'

jobs:
  sync-configurations:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ARGOCD_GITOPS_VERSIONS_DEPLOYMENT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout source repository (current repo)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we fetch all history for diffs

      - name: Checkout target repository using SSH
        uses: actions/checkout@v2
        with:
          repository: 'redreveal/argocd-gitops-versions'
          ssh-key: ${{ secrets.ARGOCD_GITOPS_VERSIONS_DEPLOYMENT_KEY }}
          path: target-repo
          ref: ${{ github.event.inputs.target_branch }}

      - name: Install Python and PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pyyaml

      - name: Compare Configuration Files Using Python Script
        run: |
          src_dir="$GITHUB_WORKSPACE/versions"
          trg_dir="$GITHUB_WORKSPACE/target-repo/versions"
          changes_detected=false

          # Find all source configuration files and compare them
          find $src_dir -name "processing-agent-config.yml" | while read src_file; do
            relative_path="${src_file#"$src_dir/"}"
            trg_file="${trg_dir}/${relative_path/processing-agent-config.yml/values.yaml}"

            if [[ -f "$trg_file" ]]; then
              # Run the custom Python script to compare configurations
              python3 ./.github/actions/scripts/drift_detection_configs.py "$src_file" "$trg_file"
              if [ $? -eq 1 ]; then
                changes_detected=true
                echo "Processing $src_file to $trg_file"
                python3 ./.github/actions/scripts/process_values_to_cm.py "$src_file" "$trg_file"
              fi
            else
              echo "Target file $trg_file does not exist. Creating and processing..."
              mkdir -p $(dirname "$trg_file")
              touch "$trg_file"
              python3 ./.github/actions/scripts/process_values_to_cm.py "$src_file" "$trg_file"
              changes_detected=true
            fi
          done

          echo "Changes detected: $changes_detected"

      - name: Commit and Push Changes to Target Repository
        if: ${{ env.changes_detected == 'true' }}
        run: |
          cd target-repo
          git config user.email "rberisha@revealdata.com"
          git config user.name "Redon Berisha"
          git add versions/
          git commit -m "Updated configurations based on changes in drift detection"
          git push
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa"
