name: Process Values and Generate ConfigMap

on:
  push:
    paths:
      - 'versions/**/processing-agent-config.yml'

jobs:
  generate-configmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install -y jq

      - name: Find Modified Config Files
        id: find_modified_files
        run: |
          # Find files modified in the last commit
          MODIFIED_FILES=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep 'versions/.*/processing-agent-config.yml' || echo "")
          echo "Modified files: $MODIFIED_FILES"
          # Prepare the list of modified files for the next step
          echo "::set-output name=modified_files::$(echo $MODIFIED_FILES)"

      - name: Process Each Modified Config File
        if: steps.find_modified_files.outputs.modified_files != ''
        run: |
          echo "Processing modified config files..."
          IFS=$'\n' read -rd '' -a modified_files <<<"${{ steps.find_modified_files.outputs.modified_files }}"
          for file in "${modified_files[@]}"; do
            if [[ -n "$file" && -f "$file" ]]; then
              echo "Processing $file..."
              python3 ./scripts/process_values_to_cm.py "$file"
            else
              echo "No file to process or file does not exist."
            fi
          done

      - name: Commit ConfigMaps to processing-agent-automation Repository
        run: |
          REPO='https://github.com/redreveal/argocd-gitops-versions.git'
          CHANGED_FILES=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep 'versions/.*/processing-agent-config.yml')
          for FILE in $CHANGED_FILES; do
            REGION_DIR=$(dirname $FILE)
            CONFIGMAP_FILE=$(basename $FILE)
            TEMP_DIR=$(mktemp -d)
            git clone ${REPO} ${TEMP_DIR}
            mkdir -p ${TEMP_DIR}/${REGION_DIR}
            cp $FILE ${TEMP_DIR}/${REGION_DIR}/
            
            cd ${TEMP_DIR}
            git add ${REGION_DIR}/${CONFIGMAP_FILE}
            git commit -m "Update ConfigMap for ${REGION_DIR}"
            git push
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
