name: Process Values and Generate ConfigMap

on:
  push:
    paths:
      - 'versions/**/processing-agent-config.yml'

jobs:
  generate-configmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install -y jq

      - name: Get List of Modified Config Files
        id: get_modified_files
        uses: actions/github-script@v5
        with:
          script: |
            const payload = context.payload;
            const repo = context.repo;
            let base, head;
            
            if (payload.pull_request) {
              base = payload.pull_request.base.sha;
              head = payload.pull_request.head.sha;
            } else {
              base = payload.before;
              head = payload.after;
            }
            
            const compare = await github.rest.repos.compareCommits({
              owner: repo.owner,
              repo: repo.repo,
              base: base,
              head: head
            });
            
            const modifiedFiles = compare.data.files.filter(file => (file.status === 'modified' || file.status === 'added') && file.filename.startsWith('versions/') && file.filename.endsWith('processing-agent-config.yml'))
              .map(file => file.filename);
            
            return modifiedFiles;

      - name: Process Each Modified Config File
        if: steps.get_modified_files.outputs.result != '[]'
        run: |
          MODIFIED_FILES=${{ steps.get_modified_files.outputs.result }}
          IFS=',' read -ra FILES <<< "$MODIFIED_FILES"
          for FILE in "${FILES[@]}"; do
            FILE="${FILE//'"'/}"  # Remove quotes
            FILE="${FILE//']'/}"  # Remove closing bracket
            FILE="${FILE//'['/}"  # Remove opening bracket
            echo "Processing $FILE"
            python3 ./scripts/process_values_to_cm.py "$FILE"
          done
        shell: bash

      - name: Commit ConfigMaps to processing-agent-automation Repository
        run: |
          REPO='https://github.com/redreveal/argocd-gitops-versions.git'
          MODIFIED_FILES=${{ steps.get_modified_files.outputs.result }}
          IFS=',' read -ra FILES <<< "$MODIFIED_FILES"
          for FILE_PATH in "${FILES[@]}"; do
            FILE_PATH="${FILE_PATH//'"'/}"  # Remove quotes
            FILE_PATH="${FILE_PATH//']'/}"  # Remove closing bracket
            FILE_PATH="${FILE_PATH//'['/}"  # Remove opening bracket
            if [[ -n "$FILE_PATH" && -f "$FILE_PATH" ]]; then
              REGION_DIR=$(dirname $FILE_PATH)
              CONFIGMAP_FILE=$(basename $FILE_PATH)
              TEMP_DIR=$(mktemp -d)
              git clone https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@${REPO#https://} $TEMP_DIR
              mkdir -p ${TEMP_DIR}/${REGION_DIR}
              cp $FILE_PATH ${TEMP_DIR}/${REGION_DIR}/
              
              cd ${TEMP_DIR}
              git config user.email "rberisha@revealdata.com"
              git config user.name "Redon Berisha"
              git add ${REGION_DIR}/${CONFIGMAP_FILE}
              git commit -m "Update ConfigMap for ${REGION_DIR}"
              git push https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@${REPO#https://}
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
